name: Check for Reviews
on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  check-reviews:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Reviewed
      id: verify_reviewers
      uses: docker://rewindio/github-action-is-pr-approved
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        REPO_ACCESS_PAT: "${{ secrets.GITHUB_TOKEN_WITH_REPO_ACCESS }}"

    - name: Print Review Status
      env:
        reviewed: ${{ steps.verify_reviewers.outputs.reviewed }}
      run:
        echo "The pr review status is $reviewed"

    - name: Apply Not Reviewed Label
      if: steps.verify_reviewers.outputs.reviewed == 'false'
      uses: actions-ecosystem/action-add-labels@v1 
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: |
          emergency-change
