name: PostgreSQL RDS Workflow

on:
  pull_request:
     branches: 
      - development
      - uat
      - release
      - main 
jobs:
  check_pull_request_body:
  
    if: ${{ contains(github.event.pull_request.body , '[x] PostgresRDS') }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     # Adding a comment for triggering PostgresRDS
      - name: Run on Postgres RDS
        run: |
          echo "Pull request body matches 'PostgresRDS'. Performing Postgres RDS Workflow..."
          
  continuous_integration:
  
      if: ${{ contains(github.event.pull_request.body , '[x] CI') }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Perform CI Workflow
          run: |
            echo "Pull request body matches 'CI', Performing CI Workflow..."
              
