name: Workflow based on Pull Request Contents

on:
  push:
    branches:
      - development
      - uat
      - release
      - main 

jobs:
  Extract_PR_data:
    runs-on: ubuntu-latest
    outputs:
      pr_data: ${{ steps.pr.outputs.pr_data }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get pull request data
        id: pr
        run: |
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].number')
          echo "pr_number: $pr_number"
          pr_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r '.body')
          echo "pr_data: $pr_data"
          echo "pr_data=${pr_data}" >> ${{ env.GITHUB_ENV }}
          
  Postgres_Deployment:
    needs: Extract_PR_data
    runs-on: ubuntu-latest
    env:
          pr_data: ${{needs.Extract_PR_data.outputs.pr_data}}
#if: ${{ contains(${{ env.pr_data }}, '[x] PostgresRDS') }}
    steps:
      - name: Deploy Postgres
        # Add the steps to deploy Postgres
        run: |
          echo "$pr_data"
          echo "Postgres deployment"
        
  Continuous_Deployment:
    needs: Extract_PR_data
    runs-on: ubuntu-latest
    env:
          pr_data: ${{needs.Extract_PR_data.outputs.pr_data}}
#if: ${{ contains(${{ env.pr_data }}, '[x] CD') }}
    steps:
      - name: Continuous Deployment
        # Add the steps to deploy Postgres
        run: |
          echo "$pr_data"
          echo "Continuous Deployment"

