name: Continuous integration

on:
  pull_request:
    branches:
      - development

jobs:
  test_dynamic_MD_file:
    if: ${{ github.base_ref == 'development' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set NAME environment variable
        id: set_name
        run: echo "NAME=Joslin" >> $GITHUB_ENV

      - name: Substitute environment variables in Markdown file
        run: |
          sed -i "s/[NAME]/${{ env.NAME }}/g" ./github/workflows/sample.md     
