name: Continuous integration

on:
  pull_request:
    branches:
      - development

jobs:
  test_dynamic_MD_file:
    if: ${{ github.base_ref == 'development' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Check dynamic md file 
      - name: Dynamic MD file
        id: md
        run: |
          export "NAME=Joslin" 
          echo "$(cat ./github/workflows/sample.md)|sed "s|[NAME]|${{ env.NAME }}|g"
          echo "NAME=${{ env.NAME }}"
