name: Continuous integration

on:
  pull_request:
    branches:
      - development

jobs:
  test_dynamic_MD_file:
    if: ${{ github.base_ref == 'development' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set NAME environment variable
        run: echo "NAME=Joslin" >> $GITHUB_ENV

      - name: Substitute environment variables in Markdown file
        run: |
          sed -e "s/\[NAME\]/${{ env.NAME }}/g" ./github.workflows/sample.md > ./sampleNEW.md

      # Use the updated sample.md file in subsequent steps
      - name: Use the updated sample.md file
        run: |
          cat ./sampleNEW.md
