on:
  pull_request:
   
jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - run: echo '${{ fromJson(env.PACKAGE_JSON).version }}'
   
