on:
   workflow_dispatch:
   
jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v3
     - id : set_var    
        run:|
         content='cat ./package.json'
         content="${content//'%'/'%25'}"
         content="${content//$'\n'/'%0A'}"
         content="${content//$'\r'/'%0D'}"
         echo "::set-output name=packageJson::$content"
         echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
      
    
