on:
  pull_request:
   
jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all Json Value 
 
    - run: |
        echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
        cat ./package.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - run: |
        echo '${{ fromJson(env.PACKAGE_JSON).version }}'
