on:
   workflow_dispatch:
   
jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JSON to variables
      uses: antifree/json-to-variables@v1.0.1
      with:
         filename: 'package.json'
         prefix: test
    - name: Show output
         run:echo "The Name was ${{ name }}, ${{ version }}"
      
    
