name: REST_api

on:
  push:
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" /orgs/josliniyda27/repos
          gh api --method POST -H "Accept: application/vnd.github+json" /orgs/josliniyda27/repos \
          -f name='Hello-World' \
          -f description='This is your first repository' \
          -f homepage='https://github.com' \
          -F private=false \
          -F has_issues=true \
          -F has_projects=true \
          -F has_wiki=true 
