name: Version
on: 
  pull_request:
jobs:
   build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world! Hey
      - run: export VERSION=$(node -p "require('./package.json').version")
      - run: echo Version is $VERSION
