name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version minor -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.NPM_AUTH_TOKEN }}@github.com/$testACtions.git" --follow-tags
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.NPM_AUTH_TOKEN }}@github.com/$testActions.git" --tags
