name: Version
on: 
  pull_request:
jobs:
   build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world! Hey
      - run: chmod +x script.sh
      - run: ./script.sh $PACKAGE_VERSION
