name: Test linux job
on:
  pull_request:

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: set_var
        run: |
          sh content='cat ./path/to/package.json'
          # the following lines are only required for multi line json
          sh content="${content//'%'/'%25'}"
          sh content="${content//$'\n'/'%0A'}"
          sh content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
