# This is a basic workflow to help you get started with Actions

name: WorkflowTriggerFromJira

# Controls when the workflow will run
on:
  # Triggers the workflow on repository_dispatch
  
 pull_request:
 #repository_dispatch:
    #event_type:[approval]

  # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Jira_Approvals:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print JIRA ticket number and environment
        run: |
          echo JIRA number is ${{ github.event.client_payload.jira-issue }}
          echo environment is ${{ github.event.client_payload.env }}
          echo Approver Nameis ${{github.event.client_payload.ApproverName}}
          echo Approved at ${{github.event.client_payload.Time}}
        

     
