name: WorkflowTriggerFromJira
on:
  # Triggers the workflow on repository_dispatch
  repository_dispatch:
    types: [ "event-triggered-by-jira" ]

jobs: 
  Jira_Approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print JIRA Pyload
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "From Jira Issue Key ${{github.event.client_payload.jirra_issue}}."
          echo "From Jira Issue Created at ${{github.event.client_payload.Time}}."
         
          
        

     
