name: WorkflowTriggerFromJira
on:
  # Triggers the workflow on repository_dispatch
  repository_dispatch:
    types: [ "event-triggered-by-jira" ]

jobs: 
  Jira_Approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print JIRA Pyload
        run: |
          echo Hello World!
          #echo Approved at ${{{{webhookResponse.body}}
          #echo JIRA number is ${{ github.event.client_payload.jira-issue }}
          #echo Approver Nameis ${{github.event.client_payload.ApproverName}}
          
        

     
